// 3D trait mesh mapping — extracted so it can be statically imported
// without pulling in the full ThreePreview component (which is lazy-loaded).

export const TRAIT_MESH_MAPPING: Record<string, Record<string, string[]>> = {
  watch: {
    sub_lantern_green: ['watch_sub_lantern_green', 'watch_sub_strap_white'],
    sub_blue: ['watch_sub_blue', 'watch_sub_strap_white'],
    argo_white: ['watch_argo_white'],
    sub_cola: ['watch_sub_cola_blue_red', 'watch_sub_strap_white'],
    sub_turquoise: ['watch_sub_turquoise', 'watch_sub_strap_white'],
    sub_bat: ['watch_sub_bat_blue_black', 'watch_sub_strap_white'],
    oyster_silver: ['watch_oyster_silver', 'watch_sub_strap_white'],
    oyster_gold: ['watch_oyster_gold', 'watch_sub_strap_gold'],
    argo_black: ['watch_argo_black'],
    sub_black: ['watch_sub_black', 'watch_sub_strap_white'],
    sub_rose: ['watch_sub_rose', 'watch_sub_strap_white'],
    timex: ['watch_timex'],
    sub_red: ['watch_sub_red', 'watch_sub_strap_gray'],
  },
  beard: {
    full: ['beard'],
    flat: ['beard_flat'],
  },
  chain: {
    silver: ['chain_silver'],
    gold: ['chain_gold'],
    onchain: ['chain_onchain'],
  },
  eyes: {
    nerd: ['eyes_normal', 'eyes_glasses', 'eyes_glasses_nerd'],
    purple_shades: ['eyes_normal', 'eyes_glasses', 'eyes_glasses_purple'],
    '3d': ['eyes_normal', 'eyes_glases_3d', 'eyes_glasses_3d_lenses', 'eyes_glases_3d_rim'],
    eye_mask: ['eyes_normal', 'eyes_eye_mask'],
    vr: ['eyes_normal', 'eyes_vr', 'eyes_vr_lense'],
    shades: ['eyes_normal', 'eyes_glasses', 'eyes_glasses_shades'],
    matrix: ['eyes_normal', 'eyes_glasses', 'eyes_glasses_shades_matrix'],
    trippy: ['eyes_normal', 'eyes_glasses', 'eyes_glasses_shades_s34n'],
    regular: ['eyes_normal'],
    metal: ['eyes_metal'],
    mfercoin: ['eyes_mfercoin'],
    red: ['eyes_red'],
    alien: ['eyes_alien'],
    zombie: ['eyes_zombie'],
    eyepatch: ['eyes_normal', 'eyes_eye_patch'],
  },
  hat_over_headphones: {
    cowboy: ['hat_cowboy_hat'],
    top: ['hat_tophat', 'hat_tophat_red'],
    pilot: ['hat_pilot_cap', 'hat_pilot_cap_rims', 'hat_pilot_cap_glasses'],
    hoodie_gray: ['shirt_hoodie_up_dark_gray', 'shirt_hoodie_dark_gray'],
    hoodie_pink: ['shirt_hoodie_up_pink', 'shirt_hoodie_pink'],
    hoodie_red: ['shirt_hoodie_up_red', 'shirt_hoodie_red'],
    hoodie_blue: ['shirt_hoodie_up_blue', 'shirt_hoodie_blue'],
    hoodie_white: ['shirt_hoodie_up_white', 'shirt_hoodie_white'],
    hoodie_green: ['shirt_hoodie_up_green', 'shirt_hoodie_green'],
    larva_mfer: ['larmf-lowpoly', 'larmf-lowpoly_1', 'larmf-lowpoly_2', 'larmf-lowpoly_3', 'larmf-lowpoly_4', 'larmf-lowpoly_5', 'larmf-lowpoly_6'],
  },
  hat_under_headphones: {
    bandana_dark_gray: ['hat_bandana_dark_gray'],
    knit_kc: ['hat_knit_kc'],
    headband_blue_green: ['headband_blue_green'],
    headband_green_white: ['headband_green_white'],
    knit_las_vegas: ['hat_knit_las_vegas'],
    cap_monochrome: ['cap_monochrome'],
    knit_new_york: ['hat_knit_new_york'],
    cap_based_blue: ['cap_based_blue'],
    cap_purple: ['cap_purple'],
    knit_san_fran: ['hat_knit_san_fran'],
    knit_miami: ['hat_knit_miami'],
    knit_chicago: ['hat_knit_chicago'],
    knit_atlanta: ['hat_knit_atlanta'],
    bandana_red: ['hat_bandana_red'],
    knit_cleveland: ['hat_knit_cleveland'],
    headband_blue_red: ['headband_blue_red'],
    knit_dallas: ['hat_knit_dallas'],
    beanie_monochrome: ['hat_beanie_monochrome'],
    headband_pink_white: ['headband_pink_white'],
    beanie: ['hat_beanie'],
    knit_baltimore: ['hat_knit_baltimore'],
    knit_buffalo: ['hat_knit_buffalo'],
    bandana_blue: ['hat_bandana_blue'],
    headband_blue_white: ['headband_blue_white'],
    knit_pittsburgh: ['hat_knit_pittsburgh'],
  },
  headphones: {
    lined: ['headphones_lined'],
    gold: ['headphones_gold'],
    blue: ['headphones_blue'],
    black: ['headphones_black'],
    pink: ['headphones_pink'],
    green: ['headphones_green'],
    white: ['headphones_white'],
    red: ['headphones_red'],
    black_square: ['headphones_square_black'],
    blue_square: ['headphones_square_blue'],
    gold_square: ['headphones_square_gold'],
  },
  long_hair: {
    long_yellow: ['hair_long_light'],
    long_black: ['hair_long_dark'],
    long_curly: ['hair_long_curly'],
  },
  mouth: {
    smile: ['mouth_smile'],
    flat: ['mouth_flat'],
  },
  shirt: {
    collared_pink: ['shirt_collared_pink'],
    collared_green: ['shirt_collared_green'],
    collared_yellow: ['shirt_collared_yellow'],
    hoodie_down_red: ['shirt_hoodie_down_red', 'shirt_hoodie_red'],
    hoodie_down_pink: ['shirt_hoodie_down_pink', 'shirt_hoodie_pink'],
    collared_white: ['shirt_collared_white'],
    collared_turquoise: ['shirt_collared_turquoise'],
    collared_blue: ['shirt_collared_blue'],
    hoodie_down_white: ['shirt_hoodie_down_white', 'shirt_hoodie_white'],
    hoodie_down_green: ['shirt_hoodie_down_green', 'shirt_hoodie_green'],
    hoodie_down_gray: ['shirt_hoodie_down_dark_gray', 'shirt_hoodie_dark_gray'],
    hoodie_down_blue: ['shirt_hoodie_down_blue', 'shirt_hoodie_blue'],
  },
  short_hair: {
    mohawk_purple: ['hair_short_mohawk_purple'],
    mohawk_red: ['hair_short_mohawk_red'],
    mohawk_pink: ['hair_short_mohawk_pink'],
    mohawk_black: ['hair_short_mohawk_black'],
    mohawk_yellow: ['hair_short_mohawk_yellow'],
    messy_black: ['hair_short_messy_black'],
    mohawk_green: ['hair_short_mohawk_green'],
    messy_yellow: ['hair_short_messy_yellow'],
    mohawk_blue: ['hair_short_mohawk_blue'],
    messy_red: ['hair_short_messy_red'],
    messy_purple: ['hair_short_messy_purple'],
  },
  smoke: {
    pipe: ['smoke_pipe'],
    pipe_brown: ['smoke_pipe_brown'],
    cig_white: ['smoke_cig_white', 'smoke'],
    cig_black: ['smoke_cig_black', 'smoke'],
  },
  type: {
    alien: ['type_alien', 'body', 'heres_my_signature'],
    charcoal: ['type_charcoal', 'body', 'heres_my_signature'],
    ape: ['type_ape', 'body', 'heres_my_signature'],
    plain: ['type_plain', 'body', 'heres_my_signature'],
    zombie: ['type_zombie', 'body', 'heres_my_signature'],
    metal: ['type_metal', 'body_metal', 'heres_my_signature'],
    based: ['type_based_mfer', 'body_mfercoin', 'heres_my_signature'],
  },
}
